const RecipesTypes = {
  FETCH_RECIPES_REQUEST: "FETCH_RECIPES_REQUEST",
  FETCH_RECIPES_ERROR: "FETCH_RECIPES_ERROR",
  FETCH_RECIPES_SUCCESS: "FETCH_RECIPES_SUCCESS",
  FETCH_RECIPE_REQUEST: "FETCH_RECIPE_REQUEST",
  FETCH_RECIPE_ERROR: "FETCH_RECIPE_ERROR",
  FETCH_RECIPE_SUCCESS: "FETCH_RECIPE_SUCCESS",
  ADD_LOCAL_RECIPE_COMMENT: "ADD_LOCAL_RECIPE_COMMENT",
  RECIPE_UPDATING: "RECIPE_UPDATING",
  RECIPE_UPDATING_ERROR: "RECIPE_UPDATING_ERROR",
};

export default RecipesTypes;
